CONTACT_EMAIL=[contact email]
CONTACT_PHONE=[contact phone]
DEPARTMENT_NAME=[name of department]
DEPARTMENT_URL=[url of department]
FLASK_APP=govuk-frontend-flask.py
FLASK_DEBUG=True
FLASK_RUN_PORT=5000
REDIS_URL=memory://
SECRET_KEY=
SERVICE_NAME=[name of service]
SERVICE_PHASE=[phase]
SERVICE_URL=[url of service]