coverage:
  status:
    project:
      app:
        target: 85%
        flags:
          - app

      opensearch_indexer:
        target: 85%
        flags:
          - opensearch_indexer

      access_copy_converter:
        target: 85%
        flags:
          - access_copy_converter

      dri_to_ayr_data_migration:
        target: 85%
        flags:
          - dri_to_ayr_data_migration
