version: '3.4'

volumes:
  keycloak_db_data:
    driver: local
  keycloak_data:
    driver: local
  webapp_db_data:
    driver: local

services:
  keycloak-db:
    image: postgres:13
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "5431:5432"
    networks:
      - local
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    command:
      - "start-dev"
    networks:
      - local
    volumes:
      - .keycloak_data:/opt/keycloak/data
  webapp-db:
    image: postgres:13
    volumes:
      - webapp_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${WEBAPP_DB_NAME}
      POSTGRES_USER: ${WEBAPP_DB_USER}
      POSTGRES_PASSWORD: ${WEBAPP_DB_PASSWORD}
    ports:
      - "5432:5432"

    networks:
      - local
  web:
    build:
      context: .
      target: release
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["manage.py", "runserver", "0.0.0.0:8000"]
    entrypoint: "python3"
    depends_on:
      - keycloak-db
      - keycloak
      - webapp-db
    volumes:
      - .:/code
    networks:
      - local

networks:
  local:
