version: '3'

volumes:
  postgres_data:
    driver: local

services:

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - local-keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - "start-dev"
    networks:
      - local-keycloak
    volumes:
    - .local/keycloak/:/opt/keycloak/data

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - keycloak
    volumes:
      - .:/app
    networks:
      - local-keycloak

networks:
  local-keycloak:
