
FROM mcr.microsoft.com/playwright/python@sha256:640d578aae63cfb632461d1b0aecb01414e4e020864ac3dd45a868dc0eff3078

WORKDIR /e2e_tests

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip wheel setuptools numpy scikit-image pillow playwright==1.55.0 python-keycloak pytest-playwright-visual==2.1.2 pytest-playwright==0.7.1 pytest-html PyJWT itsdangerous cryptography

# Accept build-time and run-time arguments
ARG GIT_REF=main
ENV GIT_REF=${GIT_REF}
ARG BROWSERS="chromium"
ENV BROWSERS=${BROWSERS}
ARG TEST_FILTER="."
ENV TEST_FILTER=${TEST_FILTER}

# Checkout the specified git ref if not main
RUN if [ "$GIT_REF" != "main" ]; then git fetch --all && git checkout "$GIT_REF"; fi

# Entrypoint script to handle parameters
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
