FROM mcr.microsoft.com/playwright/python:v1.55.0-noble

WORKDIR /e2e_tests

RUN pip install --upgrade pip wheel setuptools numpy scikit-image pillow playwright python-keycloak pytest-playwright-visual pytest-playwright pytest-html PyJWT itsdangerous cryptography

CMD ["pytest", "-vvv", "-s", ".", "--log-cli-level=DEBUG", "--base-url=https://127.0.0.1:5000", "--browser", "chromium", "--browser", "webkit", "--browser", "firefox", "--update-snapshots", "-p", "no:cacheprovider", "-o", "addopts="]
