name: Run Accessibility Tests

permissions:
  contents: read

on:
  pull_request:
  merge_group:

jobs:
  accessibility_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v3.1.1

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@8cccb8c14b6500aaffebff1aa49c502c34d2e5e6 # v2.1.0
      with:
        version: v2.40.3

    - name: Pre-build webapp image with cache
      uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
      with:
        push: false
        load: true
        tags: "da-ayr-beta-webapp:latest"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Start Docker Compose with CI-specific configuration
      run: cd local_services && docker compose -f docker-compose.ci.yml --env-file .docker.env up -d --wait --no-build || exit $(docker compose ps -q | xargs docker inspect -f '{{.State.ExitCode}}' | grep -v '^0' | wc -l)

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 20
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Set up Accessibility test environment
      env:
        KEYCLOAK_AUTH_URL_VALUE: ${{ vars.KEYCLOAK_AUTH_URL || 'http://127.0.0.1:8080/realms/tdr/protocol/openid-connect/token' }}
      run: | # pragma: allowlist secret
        cat > .env.accessibility << EOF
        AYR_AAU_USER_USERNAME=testuser
        AYR_AAU_USER_PASSWORD=password123
        KEYCLOAK_AUTH_URL=$KEYCLOAK_AUTH_URL_VALUE
        KEYCLOAK_CLIENT_ID=ayr-beta
        KEYCLOAK_CLIENT_SECRET=test-client-secret
        EOF

    - name: Run Accessibility CI
      run: |
        mkdir -p .accessibilityci
        set -a
        source .env.accessibility
        set +a
        npm run lighthouse:ci

    - name: Upload Accessibility artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: always()
      with:
        name: accessibility-report
        path: .accessibilityci/
        retention-days: 7

    - name: Check logs after test failure
      if: failure()
      run: cd local_services && docker compose -f docker-compose.ci.yml logs

    - name: Stop services
      if: always()
      run: |
        cd local_services
        docker compose -f docker-compose.ci.yml down -v
        docker system prune -f
