name: Docker Build ECR Push
on:
  push:
    branches: ['**']
  workflow_dispatch:
jobs:
  docker-build-push-ecr:
    uses: nationalarchives/da-ayr-github-actions/.github/workflows/docker-build-ecr-deploy.yml@dev
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      AWS_ECR_AND_ECR_ROLE_ARN: ${{ secrets.AWS_ECR_AND_ECR_ROLE_ARN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS.SECRET.ACCESS_KEEY }}
      AWS_REGISTRIES: ${{ secrets.AWS_REGISTRIES }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      ECR_ACCOUNT: ${{ secrets.ECR_Account }}
      WEBAPP_DB_PASSWORD: ${{ secrets.WEBAPP_DB_PASSWORD }}
      WEBAPP_DB_NAME: ${{ secrets.WEBAPP_DB_NAME }}
      WEBAPP_DB_USER: ${{ secrets.WEBAPP_DB_USER }}
      WEBAPP_DB_HOST: ${{ secrets.WEBAPP_DB_HOST }}
      WEBAPP_DEBUG: ${{ secrets.WEBAPP_DEBUG }}
      KEYCLOAK_BASE_URI: ${{ secrets.KEYCLOAK_BASE_URI }}
      KEYCLOAK_DB_NAME: ${{ secrets.KEYCLOAK_DB_NAME }}
      KEYCLOAK_DB_USER: ${{ secrets.KEYCLOAK_DB_USER }}
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      OIDC_RP_CLIENT_SECRET: ${{ secrets.OIDC_RP_CLIENT_SECRET }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
