name: Docker Build ECR Push
on:
  push:
    branches: [AYR-127]
  workflow_dispatch:
    inputs:
      docker_image_name:
        description: Docker Image is
 

jobs:
  terraform-deployment:
    uses: nationalarchives/da-ayr-gthub-actions/.github/workflows/docker-build-ecr-deploy.yml@AYR-127
    with:
      environment: ${{ inputs.docker_image_name }}
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}