name: Docker Build ECR Push
on:
  push:
    branches: [AYR-127]
  workflow_dispatch:
    inputs:
      environment:
        description: Env is 
        default: dev

jobs:
  terraform-deployment:
    uses: nationalarchives/da-ayr-gthub-actions/.github/workflows/docker-build-ecr-deploy.yml@AYR-127
    with:
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}