name: Docker Build ECR Push
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      docker_image_name:
        description: Docker Image is
jobs:
  docker-build-push-ecr:
    uses: nationalarchives/da-ayr-gthub-actions/.github/workflows/docker-build-ecr-deploy.yml@dev
    with:
      docker_image_name: ${{ inputs.docker_image_name }}
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS.SECRET.ACCESS_KEEY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      AWS_REGISTRIES: ${{ secrets.AWS_REGISTRIES }}
      ECR_ACCOUNT: ${{ secrets.ECR_Account }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      WEBAPP_DB_PASSWORD: ${{ secrets.WEBAPP_DB_PASSWORD }}
      OIDC_RP_CLIENT_SECRET: ${{ secrets.OIDC_RP_CLIENT_SECRET }}
      WEBAPP_DB_HOST: ${{ secrets.WEBAPP_DB_HOST }}
      WEBAPP_DEBUG: ${{ secrets.WEBAPP_DEBUG }}
      KEYCLOACK_BASE_URI: ${{ secrets.KEYCLOACK_BASE_URI }}
      KEYCLOACK_DB_NAME: ${{ secrets.KEYCLOACK_DB_NAME }}
      KEYCLOACK_DB_USER: ${{ secrets.KEYCLOACK_DB_USER }}
      WEBAPP_DB_NAME: ${{ secrets.WEBAPP_DB_NAME }}
      WEBAPP_DB_USER: ${{ secrets.WEBAPP_DB_USER }}
